
import type { PreferenceOption, Phone } from './types';

export const PREFERENCE_OPTIONS: PreferenceOption[] = [
  { id: 'price', label: '가격', description: '가성비 또는 프리미엄' },
  { id: 'design', label: '디자인', description: '색상, 외관, 슬림함' },
  { id: 'performance', label: '성능', description: '칩셋, RAM, 배터리' },
  { id: 'camera', label: '카메라', description: '사진 및 영상 품질' },
  { id: 'storage', label: '저장공간', description: '128GB, 256GB, 1TB 등' },
  { id: 'latest', label: '최신폰', description: '출시 1년 이내' },
  { id: 'usability', label: '사용성', description: '간단한 UI, 직관성' },
  { id: 'durability', label: '내구성', description: '방수/방진, 튼튼함' },
];

export const PHONE_DATA: Phone[] = [
    {
        "brand": "Apple",
        "model": "iPhone 15",
        "release_date": "2023-09",
        "os": "iOS",
        "soc_chip": "A16 Bionic",
        "display_size_in": 6.1,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 3349,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "6",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 171,
        "dimensions_mm": "147.6×71.6×7.8",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 15 Plus",
        "release_date": "2023-09",
        "os": "iOS",
        "soc_chip": "A16 Bionic",
        "display_size_in": 6.7,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4383,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "6",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 201,
        "dimensions_mm": "160.9×77.8×7.8",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 15 Pro",
        "release_date": "2023-09",
        "os": "iOS",
        "soc_chip": "A17 Pro",
        "display_size_in": 6.1,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 3274,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "8",
        "storage_gb_options": "128,256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 187,
        "dimensions_mm": "146.6×70.6×8.25",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 15 Pro Max",
        "release_date": "2023-09",
        "os": "iOS",
        "soc_chip": "A17 Pro",
        "display_size_in": 6.7,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4422,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "8",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 221,
        "dimensions_mm": "159.9×76.7×8.25",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 16",
        "release_date": "2024-09",
        "os": "iOS",
        "soc_chip": "A18 (est.)",
        "display_size_in": 6.1,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 3500,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "6/8",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 170,
        "dimensions_mm": "147.6×71.6×7.8",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 16 Plus",
        "release_date": "2024-09",
        "os": "iOS",
        "soc_chip": "A18 (est.)",
        "display_size_in": 6.7,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4400,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "6/8",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 200,
        "dimensions_mm": "160.9×77.8×7.8",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 16 Pro",
        "release_date": "2024-09",
        "os": "iOS",
        "soc_chip": "A18 Pro (est.)",
        "display_size_in": 6.3,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 3600,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "8",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 194,
        "dimensions_mm": "149.6×71.5×8.3",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Apple",
        "model": "iPhone 16 Pro Max",
        "release_date": "2024-09",
        "os": "iOS",
        "soc_chip": "A18 Pro (est.)",
        "display_size_in": 6.9,
        "display_type": "OLED",
        "refresh_rate_hz": "60/120",
        "peak_brightness_nits": "~2000",
        "main_camera_mp": 48,
        "telephoto_optical_zoom": "5x (Pro Max/16 Pro Max)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4600,
        "wired_charge_W": "~27",
        "wireless_charge_W": "15",
        "ram_gb": "8",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 221,
        "dimensions_mm": "163×77.6×8.3",
        "biometrics": "Face ID",
        "sim": "eSIM (지역별 상이)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C(15 시리즈+)",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass or Titanium frame",
        "warranty_months": 24,
        "sw_update_years": "5~7",
        "security_update_years": "6~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 칩셋, 생태계, 영상/사진 품질",
        "notable_cons": "고가, 커스터마이즈 제약",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S23",
        "release_date": "2023-02",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 2 for Galaxy",
        "display_size_in": 6.1,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 3900,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "8",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 168,
        "dimensions_mm": "146.3×70.9×7.6",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S23 Ultra",
        "release_date": "2023-02",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 2 for Galaxy",
        "display_size_in": 6.8,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 200,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 5000,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "8/12",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 234,
        "dimensions_mm": "163.4×78.1×8.9",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S24",
        "release_date": "2024-01",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3 for Galaxy/Exynos 2400 (region)",
        "display_size_in": 6.2,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4000,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "8",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 167,
        "dimensions_mm": "147×70.6×7.6",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S24+",
        "release_date": "2024-01",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3 for Galaxy/Exynos 2400 (region)",
        "display_size_in": 6.7,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4900,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "12",
        "storage_gb_options": "256,512",
        "ip_rating": "IP68",
        "weight_g": 196,
        "dimensions_mm": "158.5×75.9×7.7",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S24 Ultra",
        "release_date": "2024-01",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3 for Galaxy",
        "display_size_in": 6.8,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 200,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 5000,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "12",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 232,
        "dimensions_mm": "162.3×79×8.6",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy Z Flip5",
        "release_date": "2023-08",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 2 for Galaxy",
        "display_size_in": 6.7,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 12,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 3700,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "8",
        "storage_gb_options": "256,512",
        "ip_rating": "IPX8",
        "weight_g": 187,
        "dimensions_mm": "165.1×71.9×6.9 (open)",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy Z Fold5",
        "release_date": "2023-08",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 2 for Galaxy",
        "display_size_in": 7.6,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4400,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "12",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IPX8",
        "weight_g": 253,
        "dimensions_mm": "154.9×67.1×13.4 (folded)",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy Z Flip6",
        "release_date": "2024-07",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 6.7,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4000,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "8/12",
        "storage_gb_options": "256,512",
        "ip_rating": "IP48/54 (est.)",
        "weight_g": 187,
        "dimensions_mm": "open 약 165×72×6.9",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy Z Fold6",
        "release_date": "2024-07",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 7.6,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 4600,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "12",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP48/54 (est.)",
        "weight_g": 239,
        "dimensions_mm": "folded 약 153.5×68.1×12.1",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy A54",
        "release_date": "2023-03",
        "os": "Android",
        "soc_chip": "Exynos 1380",
        "display_size_in": 6.4,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 5000,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "6/8",
        "storage_gb_options": "128,256",
        "ip_rating": "IP67",
        "weight_g": 202,
        "dimensions_mm": "158.2×76.7×8.2",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Samsung",
        "model": "Galaxy A55",
        "release_date": "2024-03",
        "os": "Android",
        "soc_chip": "Exynos 1480",
        "display_size_in": 6.6,
        "display_type": "OLED (일부 A는 OLED)",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": 12,
        "front_camera_mp": 12,
        "battery_mAh": 5000,
        "wired_charge_W": "25~45",
        "wireless_charge_W": "10~15",
        "ram_gb": "8/12",
        "storage_gb_options": "128,256",
        "ip_rating": "IP67",
        "weight_g": 213,
        "dimensions_mm": "161.1×77.4×8.2",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역별)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "S Pen(울트라/폴드 일부)",
        "storage_expandable": "A시리즈 일부 No",
        "materials": "Aluminum/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "4~7",
        "security_update_years": "5~7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "다양한 라인업과 가격대, 강력한 카메라/디스플레이",
        "notable_cons": "모델별 칩/충전/업데이트 편차",
        "availability_regions": "Global"
    },
    {
        "brand": "Google",
        "model": "Pixel 7a",
        "release_date": "2023-05",
        "os": "Android",
        "soc_chip": "Tensor G2",
        "display_size_in": 6.1,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 64,
        "telephoto_optical_zoom": "5x(프로)",
        "ultrawide_mp": "48(프로/울트라급)",
        "front_camera_mp": 10.5,
        "battery_mAh": 4385,
        "wired_charge_W": "18~30",
        "wireless_charge_W": "7.5~23",
        "ram_gb": "8",
        "storage_gb_options": "128",
        "ip_rating": "IP67",
        "weight_g": 193,
        "dimensions_mm": "152×72.9×9",
        "biometrics": "지문/얼굴",
        "sim": "eSIM+Nano(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass",
        "warranty_months": 24,
        "sw_update_years": "7",
        "security_update_years": "7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "클린 안드로이드, 장기 업데이트, 사진 최적화",
        "notable_cons": "발열/충전속도 아쉬움(세대별)",
        "availability_regions": "Global(한국 정발 제한)"
    },
    {
        "brand": "Google",
        "model": "Pixel 8",
        "release_date": "2023-10",
        "os": "Android",
        "soc_chip": "Tensor G3",
        "display_size_in": 6.2,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "5x(프로)",
        "ultrawide_mp": "48(프로/울트라급)",
        "front_camera_mp": 10.5,
        "battery_mAh": 4575,
        "wired_charge_W": "18~30",
        "wireless_charge_W": "7.5~23",
        "ram_gb": "8",
        "storage_gb_options": "128,256",
        "ip_rating": "IP68",
        "weight_g": 187,
        "dimensions_mm": "150.5×70.8×8.9",
        "biometrics": "지문/얼굴",
        "sim": "eSIM+Nano(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass",
        "warranty_months": 24,
        "sw_update_years": "7",
        "security_update_years": "7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "클린 안드로이드, 장기 업데이트, 사진 최적화",
        "notable_cons": "발열/충전속도 아쉬움(세대별)",
        "availability_regions": "Global(한국 정발 제한)"
    },
    {
        "brand": "Google",
        "model": "Pixel 8a",
        "release_date": "2024-05",
        "os": "Android",
        "soc_chip": "Tensor G3",
        "display_size_in": 6.1,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 64,
        "telephoto_optical_zoom": "5x(프로)",
        "ultrawide_mp": "48(프로/울트라급)",
        "front_camera_mp": 10.5,
        "battery_mAh": 4492,
        "wired_charge_W": "18~30",
        "wireless_charge_W": "7.5~23",
        "ram_gb": "8",
        "storage_gb_options": "128,256",
        "ip_rating": "IP67",
        "weight_g": 188,
        "dimensions_mm": "152.1×72.7×8.9",
        "biometrics": "지문/얼굴",
        "sim": "eSIM+Nano(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass",
        "warranty_months": 24,
        "sw_update_years": "7",
        "security_update_years": "7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "클린 안드로이드, 장기 업데이트, 사진 최적화",
        "notable_cons": "발열/충전속도 아쉬움(세대별)",
        "availability_regions": "Global(한국 정발 제한)"
    },
    {
        "brand": "Google",
        "model": "Pixel 8 Pro",
        "release_date": "2023-10",
        "os": "Android",
        "soc_chip": "Tensor G3",
        "display_size_in": 6.7,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "5x(프로)",
        "ultrawide_mp": "48(프로/울트라급)",
        "front_camera_mp": 10.5,
        "battery_mAh": 5050,
        "wired_charge_W": "18~30",
        "wireless_charge_W": "7.5~23",
        "ram_gb": "12",
        "storage_gb_options": "128,256,512",
        "ip_rating": "IP68",
        "weight_g": 213,
        "dimensions_mm": "162.6×76.5×8.8",
        "biometrics": "지문/얼굴",
        "sim": "eSIM+Nano(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "No",
        "materials": "Aluminum/Glass",
        "warranty_months": 24,
        "sw_update_years": "7",
        "security_update_years": "7",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "클린 안드로이드, 장기 업데이트, 사진 최적화",
        "notable_cons": "발열/충전속도 아쉬움(세대별)",
        "availability_regions": "Global(한국 정발 제한)"
    },
    {
        "brand": "Xiaomi",
        "model": "14",
        "release_date": "2023-10",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 6.36,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 4610,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "8/12",
        "storage_gb_options": "256,512",
        "ip_rating": "IP68",
        "weight_g": 193,
        "dimensions_mm": "152.8×71.5×8.2",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "Xiaomi",
        "model": "14 Pro",
        "release_date": "2023-11",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 6.73,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 4880,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "12/16",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 223,
        "dimensions_mm": "161.4×75.3×8.5",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "Xiaomi",
        "model": "14 Ultra",
        "release_date": "2024-02",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 6.73,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 5300,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "12/16",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP68",
        "weight_g": 219,
        "dimensions_mm": "161.4×75.3×9.2",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "Huawei",
        "model": "Pura 70 Ultra",
        "release_date": "2024-04",
        "os": "HarmonyOS",
        "soc_chip": "Kirin (gen varies)",
        "display_size_in": 6.8,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 13,
        "battery_mAh": 5200,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "16",
        "storage_gb_options": "512,1024",
        "ip_rating": "IP68",
        "weight_g": 226,
        "dimensions_mm": "162.6×75.1×8.4",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "OnePlus",
        "model": "12",
        "release_date": "2023-12",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 6.82,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 13,
        "battery_mAh": 5400,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "12/16",
        "storage_gb_options": "256,512,1024",
        "ip_rating": "IP65",
        "weight_g": 220,
        "dimensions_mm": "164.3×75.8×9.2",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "OPPO",
        "model": "Find X7 Ultra",
        "release_date": "2024-01",
        "os": "Android",
        "soc_chip": "Snapdragon 8 Gen 3",
        "display_size_in": 6.82,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 5000,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "12/16",
        "storage_gb_options": "256,512",
        "ip_rating": "IP68",
        "weight_g": 221,
        "dimensions_mm": "164.3×76.2×9.5",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "vivo",
        "model": "X100 Pro",
        "release_date": "2023-11",
        "os": "Android",
        "soc_chip": "Dimensity 9300",
        "display_size_in": 6.78,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 5400,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "12/16",
        "storage_gb_options": "256,512",
        "ip_rating": "IP68",
        "weight_g": 221,
        "dimensions_mm": "164.1×75.3×8.9",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "Motorola",
        "model": "Edge 50 Ultra",
        "release_date": "2024-04",
        "os": "Android",
        "soc_chip": "Snapdragon 8s Gen 3",
        "display_size_in": 6.7,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 50,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 4500,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "12/16",
        "storage_gb_options": "512",
        "ip_rating": "IP68",
        "weight_g": 197,
        "dimensions_mm": "161.1×72.4×8.6",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "Motorola",
        "model": "Razr 40 Ultra (Razr+)",
        "release_date": "2023-06",
        "os": "Android",
        "soc_chip": "Snapdragon 8+ Gen 1",
        "display_size_in": 6.9,
        "display_type": "OLED",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 12,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 16,
        "battery_mAh": 3800,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "8/12",
        "storage_gb_options": "256,512",
        "ip_rating": "IP52",
        "weight_g": 188,
        "dimensions_mm": "170.8×74×6.9(open)",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    },
    {
        "brand": "Nokia",
        "model": "XR21",
        "release_date": "2023-05",
        "os": "Android",
        "soc_chip": "Snapdragon 695",
        "display_size_in": 6.67,
        "display_type": "LCD",
        "refresh_rate_hz": "120",
        "peak_brightness_nits": "~1600~3000",
        "main_camera_mp": 64,
        "telephoto_optical_zoom": "3x~10x(기종별)",
        "ultrawide_mp": "48~50",
        "front_camera_mp": 13,
        "battery_mAh": 4800,
        "wired_charge_W": "30~100",
        "wireless_charge_W": "15~80",
        "ram_gb": "6",
        "storage_gb_options": "128",
        "ip_rating": "IP69K",
        "weight_g": 231,
        "dimensions_mm": "168×78.6×10.5",
        "biometrics": "지문/얼굴",
        "sim": "Dual SIM/eSIM(지역)",
        "connectivity": "5G, Wi‑Fi, BT, USB‑C",
        "stylus_support": "No",
        "storage_expandable": "일부 microSD 지원",
        "materials": "Metal/Glass 등",
        "warranty_months": 24,
        "sw_update_years": "3~5",
        "security_update_years": "3~5",
        "msrp_krw": "",
        "street_price_krw": "",
        "price_asof": "2025-09-19",
        "notable_pros": "강력한 카메라·충전·가성비(브랜드별 특장점)",
        "notable_cons": "지역/서비스 제한, A/S 편차",
        "availability_regions": "중국/유럽/글로벌(국가별 상이)"
    }
];
